Repository utopia-rise/godot-2.5D-isometric-map-editor, pull requests merged in 2020-06, with the labels that each got.

#18 hotfix: set placeholder type update
  src/positionable/IsometricPlaceholder.cpp
Labels: bug

#19 hotfix: set default value for placeholder type
  demo/Scenes/examples/maps/types/ground.tres
  demo/Scenes/examples/maps/types/water.tres
  src/positionable/IsometricPlaceholder.cpp
  src/positionable/IsometricPlaceholder.h
Labels: bug

#20 Simplify calculus of eZ in IsometricServer
  src/IsometricServer.cpp
Labels: enhancement

#23 avoid passing in rotation mode using E key
  demo/addons/IsometricMap/Scripts/handlers/map_edition_handler.gd
Labels: bug

#24 Fixed add dimension before (V, B and N keys)
  demo/addons/IsometricMap/Scripts/handlers/map_edition_handler.gd
  src/positionable/IsometricMap.cpp
  src/positionable/IsometricMap.h
Labels: bug

#25 hotfix/enable scrolling large map
  demo/addons/IsometricMap/Scripts/stair_selector.gd
Labels: bug

#31 Adding GDNS workaround to installation documentation
  .README/INSTALL.md
  .README/png/gdns-workaround.png
Labels: documentation

#28 Hotfix/flatten change originals positions
  demo/test/unit/test_isometric_map.gd
  src/positionable/IsometricMap.cpp
Labels: bug

#27 Add release to github ci
  .github/workflows/check-pr.yaml
  .github/workflows/release.yaml
  demo/addons/IsometricMap/libs/IsometricMap.gdnlib
Labels: feature
